name: Dynamic Version Update and Build

# Workflow Dispatch allows for manual triggering with input
on:
  workflow_dispatch:
    inputs:
      snapshot_version:
        description: "SNAPSHOT Build Version"
        required: true
        default: "2.0.0-SNAPSHOT"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Create a new branch `dynamic-vars-tasks`
      - name: Create a new branch
        run: |
          git checkout -b dynamic-vars-tasks Koushik

      # Step 3: Set up JDK 8
      - name: Set up JDK 8
        uses: actions/setup-java@v3
        with:
          java-version: "8"
          distribution: "adopt"

      # Step 4: Replace the version in pom.xml with the input provided from workflow dispatch
      - name: Update POM version
        run: |
          echo "Updating POM version to ${{ github.event.inputs.snapshot_version }}"
          sed -i "s|<version>.*-SNAPSHOT</version>|<version>${{ github.event.inputs.snapshot_version }}</version>|" pom.xml

      # Step 5: Build the project using Maven
      - name: Build with Maven
        run: mvn clean package

      # Step 6: Commit and push the changes to the branch `dynamic-vars-tasks`
      - name: Commit version changes and push
        run: |
          git config --local user.name "GitHub Actions"
          git config --local user.email "actions@github.com"
          git add pom.xml
          git commit -m "Updated version to ${{ github.event.inputs.snapshot_version }}"
          git push origin dynamic-vars-tasks
